
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\nesri\OneDrive\Desktop\tkinter+Figma\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1067x727")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 727,
    width = 1067,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    533.0,
    363.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    308.0,
    364.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    759.0,
    364.0,
    image=image_image_3
)

canvas.create_text(
    603.0,
    139.0,
    anchor="nw",
    text="welcome !",
    fill="#FFFFFF",
    font=("HubotSans Bold", 60 * -1)
)

canvas.create_text(
    581.0,
    253.0,
    anchor="nw",
    text="this is a design to try the TKinter\n python library",
    fill="#FFFFFF",
    font=("HubotSans Bold", 27 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    302.5,
    495.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
   x=151.0,
    y=298.0,
    width=303.0,
    height=50.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    302.5,
    415.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
   x=151.0,
    y=298.0,
    width=303.0,
    height=50.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    302.5,
    324.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=151.0,
    y=298.0,
    width=303.0,
    height=50.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    302.5,
    235.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
   x=151.0,
    y=298.0,
    width=303.0,
    height=50.0
)

canvas.create_text(
    133.0,
    179.0,
    anchor="nw",
    text="Email :",
    fill="#FFFFFF",
    font=("HubotSans Bold", 14 * -1)
)

canvas.create_text(
    133.0,
    268.0,
    anchor="nw",
    text="user-name :",
    fill="#FFFFFF",
    font=("HubotSans Bold", 14 * -1)
)

canvas.create_text(
    133.0,
    360.0,
    anchor="nw",
    text="Phone Number :",
    fill="#FFFFFF",
    font=("HubotSans Bold", 14 * -1)
)

canvas.create_text(
    133.0,
    445.0,
    anchor="nw",
    text="Password :",
    fill="#FFFFFF",
    font=("HubotSans Bold", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=141.0,
    y=542.0,
    width=323.92578125,
    height=70.0
)

canvas.create_text(
    177.0,
    110.0,
    anchor="nw",
    text="REGISTERATION   ",
    fill="#FFFFFF",
    font=("HubotSans Bold", 26 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    834.0,
    502.75,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    612.0,
    519.0,
    image=image_image_5
)
window.resizable(False, False)
window.mainloop()
